branches:
  except:
  - "/^wip/"
language: node_js
node_js:
- '8'
script:
- yarn lint
- TZ="America/Los_Angeles" yarn test
before_install:
- yarn global add greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
- touch ./test/device-classes/*.manifest.json
after_script: greenkeeper-lockfile-upload
after_success: yarn run coverage
env:
  global:
    secure: aISzV/9BahnmgZWHU2Tk53R1rp/fFuP3WUxEb2h4LdxSpYyPeHQSAhSwjbXv6FAmI36gL7VoVQxN9P4ORNT5CSsakSZAxOd5XYi5EaHqlvDoUTwkhkef9cnbfcpg8i000KOI82PFVidKUWSiqmRX9p3rvKm4m4Fggv/f4qw7tpMZRSluz7eD7RpZTrl+7X+y5vPFVr+GGutERahuigU/iPCJqe8qEIuSxxcObd8xeMt1kLm09wBwDaxKtg7t7CY2tnp5mdeoAKy2b6Xaozms2UJtDS7h55X7BGSKKS7QNrxEx/Q14Bzs+u0zSVdKeZcAmcPl+v2gat212u9RMNEkwn1JKEfXTR7FbhmmPYyZAgCacCU0g6cGzrjm06ridUzXoG32b2qlKf/nGP7+pTUQQqBAkLiIdY72JFHRzi+SLdv4cXKMk1nV+BqqHjf697qxLAIfxDU+qAn4M8dAGw0R3yvoOXEegx3Tyf9UAB2fcDLAqZ+oE6AGE6yLnB3c2v/rpxZkCkkB1YV525hn9NqfQQNgDO0GPZSz42084J8Rnevc7ndQB+B2GES15WIgHUSc4TlXXWL3o21ArAo5Hfvphqldb0h5UprQLSTyxj5eGtK6IYxtPavXvwD6CErECfTdMF9DCgYGiJG0SFH7DmoeTkl615u2AoFvvrceccJ8kUw=
notifications:
  slack:
    secure: AOGK6gc59mOwoNlnCNPENVpaRI1dj7pnKiMMIh/MDeiBQKdMYWHDDGwyPjMYeJr5Pcme3JsDPd1icmjbtfRPv7kZEBoRMtSFRDi+127tuAG8N3eA/MB6X6rO16FmJXnfdM9YMA/7fFygU/QKbZUVtLD1OBOjdx0kIyDX4O8OwNa5Isrktj2V0GSXe2aIq/ETM3SLAfvNmIbP/mi4I0cCcdsr8GKvMy2LgGyUMh5w1F56V3Z8c8a7K2UYLtyjvGMbBEhlSiGamNDIyH/VztVpTztbNFwDAzed1QNtQ7wLMsCb2pQN9Np7T8X1pJ8zT9CXsWyFvDW+dcRTTU9fxDwefEtB0GSdMlA50o/d6P7vpoX3fIlHoFYsBpk31G0g7uFddUarhFGDscu5IbnWKdJ1vRXiBRhW3DugfudLBVbSY8rREXoXsnpUW754MxGCMH8krDgxcsgRa0IHxRVDguaaalaqdTxO+t6nFvChRY4SFedvjsmixICwgUT5GmpH4R8IE/hVPO3tb3SY3ijssoF+UJcaWIRtbLEz+5x+gHjQKkppOwltsQTJDeeaV0YGGMNaLvogoBVY0/lPL8nuOvB4KzVr+98eBAWZi4BPkfObXSG56/zBhHP6/jUi4TSETuOwsCxFZDLBCi8v5p64gXI5ST+twhhI9ZH+TA6w4puzO2k=
