language: node_js
node_js:
- '8'
script:
- yarn lint
- TZ="America/Los_Angeles" yarn test
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success: yarn run coverage
env:
  global:
    secure: aISzV/9BahnmgZWHU2Tk53R1rp/fFuP3WUxEb2h4LdxSpYyPeHQSAhSwjbXv6FAmI36gL7VoVQxN9P4ORNT5CSsakSZAxOd5XYi5EaHqlvDoUTwkhkef9cnbfcpg8i000KOI82PFVidKUWSiqmRX9p3rvKm4m4Fggv/f4qw7tpMZRSluz7eD7RpZTrl+7X+y5vPFVr+GGutERahuigU/iPCJqe8qEIuSxxcObd8xeMt1kLm09wBwDaxKtg7t7CY2tnp5mdeoAKy2b6Xaozms2UJtDS7h55X7BGSKKS7QNrxEx/Q14Bzs+u0zSVdKeZcAmcPl+v2gat212u9RMNEkwn1JKEfXTR7FbhmmPYyZAgCacCU0g6cGzrjm06ridUzXoG32b2qlKf/nGP7+pTUQQqBAkLiIdY72JFHRzi+SLdv4cXKMk1nV+BqqHjf697qxLAIfxDU+qAn4M8dAGw0R3yvoOXEegx3Tyf9UAB2fcDLAqZ+oE6AGE6yLnB3c2v/rpxZkCkkB1YV525hn9NqfQQNgDO0GPZSz42084J8Rnevc7ndQB+B2GES15WIgHUSc4TlXXWL3o21ArAo5Hfvphqldb0h5UprQLSTyxj5eGtK6IYxtPavXvwD6CErECfTdMF9DCgYGiJG0SFH7DmoeTkl615u2AoFvvrceccJ8kUw=
