language: node_js
node_js:
- '8'
script:
- yarn lint
- TZ="America/Los_Angeles" yarn test
before_install: yarn global add greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
- touch ./test/device-classes/*.manifest.json
after_script: greenkeeper-lockfile-upload
after_success: yarn run coverage
env:
  global:
    secure: aISzV/9BahnmgZWHU2Tk53R1rp/fFuP3WUxEb2h4LdxSpYyPeHQSAhSwjbXv6FAmI36gL7VoVQxN9P4ORNT5CSsakSZAxOd5XYi5EaHqlvDoUTwkhkef9cnbfcpg8i000KOI82PFVidKUWSiqmRX9p3rvKm4m4Fggv/f4qw7tpMZRSluz7eD7RpZTrl+7X+y5vPFVr+GGutERahuigU/iPCJqe8qEIuSxxcObd8xeMt1kLm09wBwDaxKtg7t7CY2tnp5mdeoAKy2b6Xaozms2UJtDS7h55X7BGSKKS7QNrxEx/Q14Bzs+u0zSVdKeZcAmcPl+v2gat212u9RMNEkwn1JKEfXTR7FbhmmPYyZAgCacCU0g6cGzrjm06ridUzXoG32b2qlKf/nGP7+pTUQQqBAkLiIdY72JFHRzi+SLdv4cXKMk1nV+BqqHjf697qxLAIfxDU+qAn4M8dAGw0R3yvoOXEegx3Tyf9UAB2fcDLAqZ+oE6AGE6yLnB3c2v/rpxZkCkkB1YV525hn9NqfQQNgDO0GPZSz42084J8Rnevc7ndQB+B2GES15WIgHUSc4TlXXWL3o21ArAo5Hfvphqldb0h5UprQLSTyxj5eGtK6IYxtPavXvwD6CErECfTdMF9DCgYGiJG0SFH7DmoeTkl615u2AoFvvrceccJ8kUw=
notifications:
  slack:
    secure: 1rha7TFwh8vPNnLwMFgb2nIY66sVnOHe89STXGzvytupIM7m4sfzYqBKIXZ8VykBaq/Os8KyezbNMOqdtbJD9XsqPD546klNN/pKgabzUp6qXmGFRNTFoZLfPDw+p4dNxmiiHBmo1xlxdtTUgCR3Bs5y47BKxlCGRZL5NuIN6Kz7jYgOR8pgu+e7Rn/8/VTm5ByhYI/qaRWTmr4t7dJehL/9rnZw7Mrxz4DDabMQXLjOnCoxAjMOmGUHG8LDkETONuV0GQUONRGR1ototXevW6jPPTi7H+JoZVZwJNuivOx+R7NgIbyQ1iVaMaNGbAeUae3BeH3yUaoEH25wpdVuYTjhSaj4yDMCO7i7bBOZ/12R4HyH4JWQpiz+XPyKSSailoaJdkQgXNuQMUCXGWjlLtK0GeA5BrKXjsHVQayPtDRbrT0Si0oiDwEmTAtk60sXyOkd1o1W8fnUKq6CNMv0GE2zzBGkccieTJ+1oMHINcB+B12YUp4gWe2JG5xIjojJcgUSgmsm2jLisO13Fy/MDCF0hfdoK5AIgdPY7wLs3tv1ZEg1EvWmEPRgF65A2grnrPbTHUAZk8AfH01wZIziMHmvykJNyhMCh5qvOX7LFcay263vZ99fW/ruhomgrOv9YSRqk+3mpDKE91zL91kel9rN0REng/vmFJy/IEf4jjE=
